// Code generated by go-swagger; DO NOT EDIT.

package bgp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// GetBgpRoutesURL generates an URL for the get bgp routes operation
type GetBgpRoutesURL struct {
	Afi       string
	Neighbor  *string
	RouterAsn *int64
	Safi      string
	TableType string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetBgpRoutesURL) WithBasePath(bp string) *GetBgpRoutesURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetBgpRoutesURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetBgpRoutesURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/bgp/routes"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	afiQ := o.Afi
	if afiQ != "" {
		qs.Set("afi", afiQ)
	}

	var neighborQ string
	if o.Neighbor != nil {
		neighborQ = *o.Neighbor
	}
	if neighborQ != "" {
		qs.Set("neighbor", neighborQ)
	}

	var routerAsnQ string
	if o.RouterAsn != nil {
		routerAsnQ = swag.FormatInt64(*o.RouterAsn)
	}
	if routerAsnQ != "" {
		qs.Set("router_asn", routerAsnQ)
	}

	safiQ := o.Safi
	if safiQ != "" {
		qs.Set("safi", safiQ)
	}

	tableTypeQ := o.TableType
	if tableTypeQ != "" {
		qs.Set("table_type", tableTypeQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetBgpRoutesURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetBgpRoutesURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetBgpRoutesURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetBgpRoutesURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetBgpRoutesURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetBgpRoutesURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
