// Code generated by go-swagger; DO NOT EDIT.

// Package server Cilium API
//
//	Cilium
//	Schemes:
//	  unix
//	Host: localhost
//	BasePath: /v1
//	Version: v1beta1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/octet-stream
//	  - application/json
//
// swagger:meta
package server
