// Code generated by go-swagger; DO NOT EDIT.

// Package server dolphin operator
//
//	The API for the dolphin operator project
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package server
