// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The API for the dolphin operator project",
    "title": "dolphin operator",
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/healthz": {
      "get": {
        "tags": [
          "operator"
        ],
        "summary": "retrieve health",
        "responses": {
          "200": {
            "description": "operator is healthy",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "operator is not healthy",
            "schema": {
              "type": "string"
            }
          },
          "501": {
            "description": "operator healthy data is not retrievable",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/metrics/": {
      "get": {
        "description": "returns all operator metrics",
        "tags": [
          "metrics"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "500": {
            "description": "could not retrieve metrics"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The API for the dolphin operator project",
    "title": "dolphin operator",
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/healthz": {
      "get": {
        "tags": [
          "operator"
        ],
        "summary": "retrieve health",
        "responses": {
          "200": {
            "description": "operator is healthy",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "operator is not healthy",
            "schema": {
              "type": "string"
            }
          },
          "501": {
            "description": "operator healthy data is not retrievable",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/metrics/": {
      "get": {
        "description": "returns all operator metrics",
        "tags": [
          "metrics"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "500": {
            "description": "could not retrieve metrics"
          }
        }
      }
    }
  }
}`))
}
